In [1]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha", "Karan"],
    "Age": [21, 22, 20, 23, 24],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)

In [2]:
df.to_csv("students.csv", index=False)

In [4]:
df2 = pd.read_csv("students.csv")  
df2

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Rahul   20     78
3  Sneha   23     88
4  Karan   24     92

In [5]:
df2.head()

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Rahul   20     78
3  Sneha   23     88
4  Karan   24     92

In [6]:
df2.info()
df2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

             Age      Marks
count   5.000000   5.000000
mean   22.000000  86.600000
std     1.581139   5.458938
min    20.000000  78.000000
25%    21.000000  85.000000
50%    22.000000  88.000000
75%    23.000000  90.000000
max    24.000000  92.000000

In [7]:
df2[df2["Marks"] > 85]
df2.sort_values(by="Marks", ascending=False)

    Name  Age  Marks
4  Karan   24     92
1   Riya   22     90
3  Sneha   23     88
0   Aman   21     85
2  Rahul   20     78

In [8]:
#Checking missing values 
df2.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

In [11]:
#Add New Column
df2["Status"] = df2["Marks"].apply(
    lambda x: "Excellent" if x > 85 else "Average"
)
df2["Status"]

0      Average
1    Excellent
2      Average
3    Excellent
4    Excellent
Name: Status, dtype: object

In [13]:
df2.rename(columns={"Marks": "Score"}, inplace=True)

In [14]:
df2.drop("Age", axis=1, inplace=True)

In [15]:
df2.sort_values(by="Score", ascending=False)

    Name  Score     Status
4  Karan     92  Excellent
1   Riya     90  Excellent
3  Sneha     88  Excellent
0   Aman     85    Average
2  Rahul     78    Average

In [16]:
df2["Status"].value_counts()

Status
Excellent    3
Average      2
Name: count, dtype: int64

Performed CSV operations, handled missing values, created new features,
grouped data, and analyzed dataset using Pandas.