In [2]:
import pandas as pd

In [3]:
data = {                                                    #Create simple Dataset 
    "Name": ["Aman", "Riya", "Rahul", "Sneha"],
    "Age": [21, 22, 20, 23],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Rahul   20     78
3  Sneha   23     88

In [8]:
len(df)

4

In [4]:
df.head()      #Show First five rows

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Rahul   20     78
3  Sneha   23     88

In [5]:
df.tail()     #Show last five rows

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
2  Rahul   20     78
3  Sneha   23     88

In [6]:
df["Name"]

0     Aman
1     Riya
2    Rahul
3    Sneha
Name: Name, dtype: object

In [9]:
df[["Name", "Marks"]]

    Name  Marks
0   Aman     85
1   Riya     90
2  Rahul     78
3  Sneha     88

In [10]:
df[df["Marks"] > 80]           #Filter data

    Name  Age  Marks
0   Aman   21     85
1   Riya   22     90
3  Sneha   23     88

In [11]:
df.describe()                #Basic stats

             Age      Marks
count   4.000000   4.000000
mean   21.500000  85.250000
std     1.290994   5.251984
min    20.000000  78.000000
25%    20.750000  83.250000
50%    21.500000  86.500000
75%    22.250000  88.500000
max    23.000000  90.000000

In [12]:
#use Pandas to create and analyze a dataset using DataFrame